import os
import requests
import pandas as pd
import streamlit as st

st.set_page_config(
    page_title="IntelliTraffic API Dashboard",
    page_icon="🚦",
    layout="wide"
)

# -------------------------------------------------
# API URL CONFIG
# Local default: FastAPI running on your laptop
# Streamlit Cloud: use demo fallback if API not available
# Future: add API_BASE_URL in Streamlit secrets
# -------------------------------------------------

def get_api_base_url():
    try:
        return st.secrets.get(
            "API_BASE_URL",
            os.getenv("API_BASE_URL", "http://127.0.0.1:8000")
        )
    except Exception:
        return os.getenv("API_BASE_URL", "http://127.0.0.1:8000")


API_BASE_URL = get_api_base_url()


# -------------------------------------------------
# DEMO FALLBACK DATA
# -------------------------------------------------

DEMO_HEALTH = {
    "status": "demo",
    "message": "Running in Streamlit demo mode"
}

DEMO_ANALYTICS = {
    "total_violations": 2,
    "wrong_side_cases": 1,
    "helmet_violations": 1,
    "evidence_generated": 2
}

DEMO_RECORDS = [
    {
        "violation_id": "V001",
        "violation_type": "Wrong-Side Driving",
        "location": "Flyover Road",
        "status": "Violation Detected",
        "evidence": "Generated",
        "timestamp": "2026-06-21 06:06:39"
    },
    {
        "violation_id": "V002",
        "violation_type": "No Helmet",
        "location": "Traffic Road",
        "status": "Violation Detected",
        "evidence": "Generated",
        "timestamp": "2026-06-21 06:15:00"
    }
]


def fetch_json(endpoint, fallback):
    url = f"{API_BASE_URL}{endpoint}"

    try:
        response = requests.get(url, timeout=4)

        if response.status_code == 200:
            return response.json(), True, None

        return fallback, False, f"API returned status code {response.status_code}"

    except Exception as error:
        return fallback, False, str(error)


# -------------------------------------------------
# DASHBOARD UI
# -------------------------------------------------

st.title("🚦 IntelliTraffic API Dashboard")

st.write(
    "Dashboard for traffic violation records, analytics, and evidence generated by the AI prototype."
)

st.markdown("---")

health, api_connected, api_error = fetch_json("/health", DEMO_HEALTH)

if api_connected:
    st.success(f"API Connected Successfully: {API_BASE_URL}")
else:
    st.warning(
        "API backend is not connected. Showing demo dashboard data for deployment preview."
    )

    with st.expander("API Details"):
        st.write("Current API URL:")
        st.code(API_BASE_URL)
        st.write("Error:")
        st.code(api_error)

st.markdown("---")

analytics, analytics_connected, _ = fetch_json("/analytics", DEMO_ANALYTICS)

total_violations = analytics.get("total_violations", 2)
wrong_side_cases = analytics.get("wrong_side_cases", 1)
helmet_violations = analytics.get("helmet_violations", 1)
evidence_generated = analytics.get("evidence_generated", 2)

col1, col2, col3, col4 = st.columns(4)

col1.metric("Total Violations", total_violations)
col2.metric("Wrong-Side Cases", wrong_side_cases)
col3.metric("Helmet Violations", helmet_violations)
col4.metric("Evidence Generated", evidence_generated)

st.markdown("---")

st.subheader("📊 Violation Records")

records_response, records_connected, _ = fetch_json(
    "/violations",
    {"records": DEMO_RECORDS}
)

records = records_response.get("records", DEMO_RECORDS)

df = pd.DataFrame(records)

st.dataframe(df, use_container_width=True)

st.markdown("---")

st.subheader("🧠 Detection Modules")

left, right = st.columns(2)

with left:
    st.markdown("### Flyover Wrong-Side Detection")
    st.write(
        """
        - Detects vehicles in flyover footage  
        - Tracks vehicle movement direction  
        - Compares movement with valid road direction  
        - Marks violation if vehicle moves opposite  
        - Generates evidence frame  
        """
    )

with right:
    st.markdown("### Helmet Violation Detection")
    st.write(
        """
        - Detects motorcycle riders  
        - Identifies possible no-helmet cases  
        - Marks violation on video frame  
        - Saves evidence for review  
        - Helps reduce manual monitoring  
        """
    )

st.markdown("---")

st.subheader("⚙️ System Workflow")

st.code(
    """
Traffic Video
     ↓
OpenCV Frame Processing
     ↓
YOLO Object Detection
     ↓
Violation Logic
     ↓
Evidence Frame Generation
     ↓
FastAPI / Demo API Records
     ↓
Streamlit Dashboard
    """,
    language="text"
)

st.markdown("---")

st.subheader("🚀 Local Run Instructions")

st.code(
    """
# Terminal 1: Start FastAPI backend
python -m uvicorn backend_api:app --reload --port 8000

# Terminal 2: Start API dashboard
python -m streamlit run api_dashboard.py
    """,
    language="bash"
)

st.markdown("---")

st.subheader("📦 Repository")

st.write("GitHub Repository:")
st.code("https://github.com/Mrigank-loop/Get-Rid-of-Traffic-vioaltions")

st.success("API dashboard ready for Streamlit deployment.")